class Statement {
  constructor (side, truth) {
    this.side = side

    if (truth) {
      this.truth = 1
      this.not = new Statement(side, false)
    } else {
      this.truth = -1
    }
  }

  get d2 () { return { side: this.side, truth: this.truth, d: 'd2' } }
  get d3 () { return { side: this.side, truth: this.truth, d: 'd3' } }
  get d4 () { return { side: this.side, truth: this.truth, d: 'd4' } }
  get d5 () { return { side: this.side, truth: this.truth, d: 'd5' } }
}

const x = new Statement(0, true)
const y = new Statement(1, true)
const z = new Statement(2, true)

module.exports = {
  'xN': [
    { _if: [], _then: z.not.d2 },
    { _if: [ x.not.d2 ], _then: y.d2 },
    { _if: [ x.d2 ], _then: y.not.d2 },
    { _if: [ y.not.d2 ], _then: x.d2 },
    { _if: [ y.d2 ], _then: x.not.d2 },
    { _if: [ x.d2 ], _then: x.d4 },
    { _if: [ y.d2 ], _then: y.d4 },
    { _if: [ x.d4 ], _then: x.d2 },
    { _if: [ y.d4 ], _then: y.d2 },
    { _if: [ x.d3 ], _then: y.not.d3 },
    { _if: [ x.not.d3 ], _then: y.d3 },
    { _if: [ y.d3 ], _then: x.not.d3 },
    { _if: [ y.not.d3 ], _then: x.d3 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 },
    { _if: [ x.d5 ], _then: y.not.d5 },
    { _if: [ x.d5 ], _then: z.not.d5 },
    { _if: [ y.d5 ], _then: x.not.d5 },
    { _if: [ y.d5 ], _then: z.not.d5 },
    { _if: [ z.d5 ], _then: x.not.d5 },
    { _if: [ z.d5 ], _then: y.not.d5 },
    { _if: [ x.not.d5, y.not.d5 ], _then: z.d5 },
    { _if: [ x.not.d5, z.not.d5 ], _then: y.d5 },
    { _if: [ y.not.d5, z.not.d5 ], _then: x.d5 }
  ],
  'x2': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [ x.d3 ], _then: y.not.d3 },
    { _if: [ x.not.d3 ], _then: y.d3 },
    { _if: [ y.d3 ], _then: x.not.d3 },
    { _if: [ y.not.d3 ], _then: x.d3 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 },
    { _if: [ x.d5 ], _then: y.not.d5 },
    { _if: [ x.d5 ], _then: z.not.d5 },
    { _if: [ y.d5 ], _then: x.not.d5 },
    { _if: [ y.d5 ], _then: z.not.d5 },
    { _if: [ z.d5 ], _then: x.not.d5 },
    { _if: [ z.d5 ], _then: y.not.d5 },
    { _if: [ x.not.d5, y.not.d5 ], _then: z.d5 },
    { _if: [ x.not.d5, z.not.d5 ], _then: y.d5 },
    { _if: [ y.not.d5, z.not.d5 ], _then: x.d5 }
  ],
  'x3': [
    { _if: [], _then: z.not.d2 },
    { _if: [], _then: x.d3 },
    { _if: [], _then: y.d3 },
    { _if: [], _then: z.d3 },
    { _if: [ x.not.d2 ], _then: y.d2 },
    { _if: [ x.d2 ], _then: y.not.d2 },
    { _if: [ y.not.d2 ], _then: x.d2 },
    { _if: [ y.d2 ], _then: x.not.d2 },
    { _if: [ x.d2 ], _then: x.d4 },
    { _if: [ y.d2 ], _then: y.d4 },
    { _if: [ x.d4 ], _then: x.d2 },
    { _if: [ y.d4 ], _then: y.d2 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 },
    { _if: [ x.d5 ], _then: y.not.d5 },
    { _if: [ x.d5 ], _then: z.not.d5 },
    { _if: [ y.d5 ], _then: x.not.d5 },
    { _if: [ y.d5 ], _then: z.not.d5 },
    { _if: [ z.d5 ], _then: x.not.d5 },
    { _if: [ z.d5 ], _then: y.not.d5 },
    { _if: [ x.not.d5, y.not.d5 ], _then: z.d5 },
    { _if: [ x.not.d5, z.not.d5 ], _then: y.d5 },
    { _if: [ y.not.d5, z.not.d5 ], _then: x.d5 }
  ],
  'x4': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d4 },
    { _if: [], _then: y.d4 },
    { _if: [], _then: z.d4 },
    { _if: [ x.d3 ], _then: y.not.d3 },
    { _if: [ x.not.d3 ], _then: y.d3 },
    { _if: [ y.d3 ], _then: x.not.d3 },
    { _if: [ y.not.d3 ], _then: x.d3 },
    { _if: [ x.d5 ], _then: y.not.d5 },
    { _if: [ x.d5 ], _then: z.not.d5 },
    { _if: [ y.d5 ], _then: x.not.d5 },
    { _if: [ y.d5 ], _then: z.not.d5 },
    { _if: [ z.d5 ], _then: x.not.d5 },
    { _if: [ z.d5 ], _then: y.not.d5 },
    { _if: [ x.not.d5, y.not.d5 ], _then: z.d5 },
    { _if: [ x.not.d5, z.not.d5 ], _then: y.d5 },
    { _if: [ y.not.d5, z.not.d5 ], _then: x.d5 }
  ],
  'x5': [
    { _if: [], _then: z.not.d2 },
    { _if: [], _then: x.d5 },
    { _if: [], _then: y.d5 },
    { _if: [], _then: z.d5 },
    { _if: [ x.not.d2 ], _then: y.d2 },
    { _if: [ x.d2 ], _then: y.not.d2 },
    { _if: [ y.not.d2 ], _then: x.d2 },
    { _if: [ y.d2 ], _then: x.not.d2 },
    { _if: [ x.d2 ], _then: x.d4 },
    { _if: [ y.d2 ], _then: y.d4 },
    { _if: [ x.d4 ], _then: x.d2 },
    { _if: [ y.d4 ], _then: y.d2 },
    { _if: [ x.d3 ], _then: y.not.d3 },
    { _if: [ x.not.d3 ], _then: y.d3 },
    { _if: [ y.d3 ], _then: x.not.d3 },
    { _if: [ y.not.d3 ], _then: x.d3 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 }
  ],
  'x2 x3': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d3 },
    { _if: [], _then: y.d3 },
    { _if: [], _then: z.d3 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 },
    { _if: [ x.d5 ], _then: y.not.d5 },
    { _if: [ x.d5 ], _then: z.not.d5 },
    { _if: [ y.d5 ], _then: x.not.d5 },
    { _if: [ y.d5 ], _then: z.not.d5 },
    { _if: [ z.d5 ], _then: x.not.d5 },
    { _if: [ z.d5 ], _then: y.not.d5 },
    { _if: [ x.not.d5, y.not.d5 ], _then: z.d5 },
    { _if: [ x.not.d5, z.not.d5 ], _then: y.d5 },
    { _if: [ y.not.d5, z.not.d5 ], _then: x.d5 }
  ],
  'x2 x5': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d5 },
    { _if: [], _then: y.d5 },
    { _if: [], _then: z.d5 },
    { _if: [ x.d3 ], _then: y.not.d3 },
    { _if: [ x.not.d3 ], _then: y.d3 },
    { _if: [ y.d3 ], _then: x.not.d3 },
    { _if: [ y.not.d3 ], _then: x.d3 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 }
  ],
  'x3 x4': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d3 },
    { _if: [], _then: y.d3 },
    { _if: [], _then: z.d3 },
    { _if: [], _then: x.d4 },
    { _if: [], _then: y.d4 },
    { _if: [], _then: z.d4 },
    { _if: [ x.d5 ], _then: y.not.d5 },
    { _if: [ x.d5 ], _then: z.not.d5 },
    { _if: [ y.d5 ], _then: x.not.d5 },
    { _if: [ y.d5 ], _then: z.not.d5 },
    { _if: [ z.d5 ], _then: x.not.d5 },
    { _if: [ z.d5 ], _then: y.not.d5 },
    { _if: [ x.not.d5, y.not.d5 ], _then: z.d5 },
    { _if: [ x.not.d5, z.not.d5 ], _then: y.d5 },
    { _if: [ y.not.d5, z.not.d5 ], _then: x.d5 }
  ],
  'x3 x5': [
    { _if: [], _then: z.not.d2 },
    { _if: [], _then: x.d3 },
    { _if: [], _then: y.d3 },
    { _if: [], _then: z.d3 },
    { _if: [], _then: x.d5 },
    { _if: [], _then: y.d5 },
    { _if: [], _then: z.d5 },
    { _if: [ x.not.d2 ], _then: y.d2 },
    { _if: [ x.d2 ], _then: y.not.d2 },
    { _if: [ y.not.d2 ], _then: x.d2 },
    { _if: [ y.d2 ], _then: x.not.d2 },
    { _if: [ x.d2 ], _then: x.d4 },
    { _if: [ y.d2 ], _then: y.d4 },
    { _if: [ x.d4 ], _then: x.d2 },
    { _if: [ y.d4 ], _then: y.d2 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 }
  ],
  'x4 x5': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d4 },
    { _if: [], _then: y.d4 },
    { _if: [], _then: z.d4 },
    { _if: [], _then: x.d5 },
    { _if: [], _then: y.d5 },
    { _if: [], _then: z.d5 },
    { _if: [ x.d3 ], _then: y.not.d3 },
    { _if: [ x.not.d3 ], _then: y.d3 },
    { _if: [ y.d3 ], _then: x.not.d3 },
    { _if: [ y.not.d3 ], _then: x.d3 }
  ],
  'x2 x3 x5': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d3 },
    { _if: [], _then: y.d3 },
    { _if: [], _then: z.d3 },
    { _if: [], _then: x.d5 },
    { _if: [], _then: y.d5 },
    { _if: [], _then: z.d5 },
    { _if: [ x.d4 ], _then: y.not.d4 },
    { _if: [ x.not.d4 ], _then: y.d4 },
    { _if: [ y.d4 ], _then: x.not.d4 },
    { _if: [ y.not.d4 ], _then: x.d4 }
  ],
  'x3 x4 x5': [
    { _if: [], _then: x.d2 },
    { _if: [], _then: y.d2 },
    { _if: [], _then: z.d2 },
    { _if: [], _then: x.d3 },
    { _if: [], _then: y.d3 },
    { _if: [], _then: z.d3 },
    { _if: [], _then: x.d4 },
    { _if: [], _then: y.d4 },
    { _if: [], _then: z.d4 },
    { _if: [], _then: x.d5 },
    { _if: [], _then: y.d5 },
    { _if: [], _then: z.d5 }
  ]
}
